apiVersion: v1
kind: ConfigMap
metadata:
  name: rating-service-config
data:
  application.yaml: |
    spring:
      application:
        name: rating-service
      datasource:
        url: jdbc:postgresql://${PG_DB_HOST:postgresdb}:${PG_DB_PORT:5432}/${POSTGRES_DB_RATING_SERVICE:rating_service_db}
        username: ${PG_DB_USERNAME_RATING_SERVICE:rating_service}
        password: ${PG_DB_PASS_RATING_SERVICE:rating_service}
        driver-class-name: org.postgresql.Driver
      liquibase:
        change-log: classpath:db/changelog/liquibase-master.yaml
        enabled: true
      jpa:
        hibernate:
          ddl-auto: none
        show-sql: false
        open-in-view: false
      security:
        oauth2:
          client:
            registration:
              all-in-market:
                client-id: ${OAUTH2_CLIENT_ID:clientId}
                client-secret: ${OAUTH2_CLIENT_SECRET:secret}
                authorization-grant-type: ${OAUTH2_CLIENT_GRANT_TYPE:client_credentials}
                client-authentication-method: ${OAUTH2_CLIENT_AUTH_METHOD:client_secret_basic}
            provider:
              all-in-market:
                token-uri: ${OAUTH2_CLIENT_TOKEN_URI:http://localhost:7070/oauth2/token}
      kafka:
        bootstrap-servers: kafka:9092
        topics:
          category-changed: ${KAFKA_TOPIC_CATEGORY_CHANGED:category_changed}
          category-attribute-changed: ${KAFKA_TOPIC_CATEGORY_ATTRIBUTE_CHANGED:category_attribute_changed}
          registration-success: ${KAFKA_TOPIC_REGISTRATION_SUCCESS:registration_success}
          status-order-changed: ${KAFKA_TOPIC_STATUS_ORDER_CHANGED:status_order_changed}
          status-payment-changed: ${KAFKA_TOPIC_STATUS_PAYMENT_CHANGED:status_payment_changed}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rating-service
  labels:
    app: rating-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rating-service
  template:
    metadata:
      name: rating-service
      labels:
        app: rating-service
    spec:
      containers:
        - name: rating-service
          image: albertsereda/all-in-market-rating-service
          imagePullPolicy: Always
          env:
            - name: SPRING_CONFIG_IMPORT
              value: file:/config/
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: rating-service-config
              mountPath: /config
      volumes:
        - name: rating-service-config
          configMap:
            name: rating-service-config
      restartPolicy: Always